version: "3"

services:
  nginx:
    image: nginx
    restart: always
    depends_on:
#      - web-client
      - web-server
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

#  web-client:
#    profiles:
#      - donotstart

  web-server:
    build:
      context: .
      dockerfile: backend/Dockerfile
      network: host
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - backend/.env
    environment:
      REDIS_HOST: "redis"
      REDIS_PASSOWRD: 6379
    volumes:
      - proj-db-volume:/usr/src/app/instance
#    networks:
#      - host
    network_mode: host
#    extra_hosts:
#      - "host.docker.internal:host-gateway"


  celery:
    build:
      context: .
      dockerfile: backend/api/celery/Dockerfile
    restart: unless-stopped
    depends_on:
      - web-server
    env_file:
      - backend/.env
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/1"
      CELERY_RESULT_BACKED: "redis://redis:6379/1"
    volumes:
      - proj-db-volume:/usr/src/app/instance

  redis:
    image: redis
    restart: always
    command: redis-server
    expose:
      - "6379"

volumes:
  proj-db-volume:

#networks:
#  host:
#    external: True