version: "3"

services:
  nginx:
    image: nginx
    restart: always
    depends_on:
      - web-server
    ports:
      - "8000:8000"
    volumes:
      - files-volume:/usr/src/app/files
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf

  web-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    restart: unless-stopped
    container_name: web-server-container
    depends_on:
      - redis
      - postgres
      - ldap-server
    links:
      - postgres
    env_file:
      - ${BACKEND_ENV}
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      POSTGRES_HOST: "postgres"
      LDAP_HOSTS: "ldap-server"
    expose:
      - "5000"
    volumes:
      - $HOME/.cache/pip:/root/.cache/pip
      - files-volume:/usr/src/app/backend/files

  web-celery:
    build:
      context: ./backend
      dockerfile: api/celery_app/Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    restart: unless-stopped
    container_name: web-celery-container
    depends_on:
      - web-server
      - redis
      - postgres
    links:
      - postgres
    env_file:
      - ${BACKEND_ENV}
    environment:
      CELERY_BROKER_URL: "redis://default:${REDIS_PASSWORD}@redis:6379/1"
      CELERY_RESULT_BACKED: "redis://default:${REDIS_PASSWORD}@redis:6379/1"
      POSTGRES_HOST: "postgres"
    volumes:
      - $HOME/.cache/pip:/root/.cache/pip

  redis:
    image: redis
    container_name: redis-container
    restart: always
    env_file:
      - ${BACKEND_ENV}
    command: bash -c  "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    expose:
      - "6379"

  ldap-server:
    build:
      context: ./backend/ldap
      dockerfile: Dockerfile
    container_name: ldap-server-container
    environment:
      LDAP_ORGANISATION: "People"
      LDAP_ADMIN_PASSWORD: "1234"
      LDAP_DOMAIN: "example.com"

  postgres:
    image: postgres
    container_name: postgres-container
    restart: unless-stopped
    expose:
      - "${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data/
    command: -p $POSTGRES_PORT

volumes:
  files-volume:
  postgres-db-volume: