version: "3"

services:
  nginx:
    image: nginx
    restart: always
    depends_on:
#      - web-client
      - web-server
    ports:
      - "8082:8080"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

#  web-client:
#    profiles:
#      - donotstart

  web-server:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    container_name: web-server

    depends_on:
      - redis
    env_file:
      - backend/.env
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    volumes:
      - proj-db-volume:/usr/src/app/instance

  web-celery:
    build:
      context: .
      dockerfile: backend/api/celery/Dockerfile
    restart: unless-stopped
    container_name: web-celery
    depends_on:
      - web-server
    env_file:
      - backend/.env
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/1"
      CELERY_RESULT_BACKED: "redis://redis:6379/1"
    volumes:
      - proj-db-volume:/usr/src/app/instance

  redis:
    image: redis
    restart: always
    command: redis-server
    expose:
      - "6379"

  ldap:
    build:
      context: .
      dockerfile: backend/ldap-conf/Dockerfile
    environment:
      LDAP_ORGANISATION: "People"
      LDAP_ADMIN_PASSWORD: "1234"
      LDAP_DOMAIN: "example.com"
    ports:
      - "0.0.0.0:389:389"
    profiles: ['ldap']

volumes:
  proj-db-volume:
